### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by xackery** [529124368/golang_3D_Game#1]
Is it ok for me to use it on one of my repos? namely. man.gltf was made in this. Is this open source and I have permission?

**Comment by 529124368** [comment]
@xackery 
Hello, about man.gltf, you can use it with any of your game demos, but please don't use it for commercial purposes, because this model is also obtained from the Internet for free and is not my property.

**Comment by xackery** [comment]
Ok thank you! I am just using it for testing on an open source project https://github.com/xackery/quail and just wanted to be sure before I versioned it
